services:

  postgres:
    image: postgres:16
    container_name: expense-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build: .
    container_name: expense-app

    ports:
      - "8080:8080"

    environment:

      # Database
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # JWT
      JWT_SECRET: ${JWT_SECRET}

      # Mailtrap
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      # File uploads
      UPLOAD_DIR: ${UPLOAD_DIR}

    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: